[package]
name = "maths_programming"
version = "0.1.0"
authors = ["meddion <volodia23byk@gmail.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.21.0"
plotters = "^0.2.12"
rand = "0.7.3"
image = "0.23.3"

[dev-dependencies]
criterion = "0.3.1"

[[bench]]
name = "fibonacci"
harness = false